Geo code 
* geo code for brazil 
* Goal: tale scrape long, lat
* scrape and verify if its lat and long

In [88]:
API_KEY = "AIzaSyD_-qwjnfnhTBczSUftL_bGroJ1lJk1z0k"

In [102]:
import pandas as pd 
import requests 
import time

file = 'UgandaColleges.csv'
df = pd.read_csv('UgandaColleges.csv')
df

,Unnamed: 0,college,unitype,estyr,district,latitude,longitude,city
0,0,Busitema University,public,2007.0,NaN,0.545462,34.020027,NaN
1,1,Gulu University,public,2002.0,NaN,2.788685,32.316868,NaN
2,2,Kabale University,public,2005.0,NaN,-1.241623,29.985659,NaN
3,3,Valley University of Science & Technology,private,2015.0,Bushenyi,-0.547900,30.201128,NaN
4,4,Victoria University,private,2010.0,NaN,0.313821,32.589170,NaN
5,5,Virtual University of Uganda,private,2011.0,Kampala,0.301614,32.605907,NaN
6,6,Kyambogo University,public,2002.0,NaN,0.353579,32.630215,NaN
7,7,Lira University,public,2015.0,NaN,2.251234,32.821014,NaN
8,8,Makerere University,public,1922.0,NaN,0.329507,32.571056,NaN
9,9,Mbarara University of Science and Technology,public,1989.0,NaN,-0.616499,30.656788,NaN
10,10,Muni University,public,2013.0,NaN,2.996486,30.926823,NaN
11,11,Soroti University,public,2015.0,NaN,1.765941,33.628796,NaN
12,12,Africa Renewal University,private,2013.0,Buloba-Mityana Road,0.326284,32.440525,NaN
13,13,African Bible University,private,2005.0,NaN,0.241361,32.564840,NaN
14,14,African Rural University,private,2011.0,Kibaale,0.942175,30.819237,NaN
15,15,Aga Khan University,private,2001.0,Kampala,0.320824,32.568980,NaN
16,16,"All Saints University, Lango",private,2008.0,Lira,2.246437,32.899900,NaN
17,17,Ankole Western University,private,2016.0,Sheema,-0.573634,30.381319,NaN
18,18,Avance International University,private,2016.0,Wakiso,0.357508,32.541480,NaN
19,19,Bishop Stuart University,private,2006.0,Mbarara,-0.604102,30.694262,NaN
20,20,Bugema University,private,1994.0,Luwero,0.570542,32.643784,NaN
21,21,Cavendish University,private,2008.0,Kampala,0.301162,32.593388,NaN
22,22,Clarke International University,private,2008.0,Kampala,0.305589,32.610924,NaN
23,23,Fins Medical University,private,2018.0,Kabrole,0.661393,30.265170,NaN
24,24,Ibanda University,private,2014.0,Ibanda,-0.122621,30.500774,NaN
25,25,"International Business, Science, & Technology ...",private,2011.0,Kampala,0.334517,32.601337,NaN
26,26,International University of East Africa,private,2010.0,Kampala,0.286043,32.607834,NaN
27,27,Islamic Call University College,private,2011.0,Kampala,0.315949,32.567620,NaN
28,28,Islamic University in Uganda,private,1988.0,Mbale,1.103777,34.174255,NaN
29,29,Kampala International University,private,2001.0,Kampala,0.294823,32.605040,NaN
30,30,Kampala University,private,2000.0,Kampala,0.281009,32.540900,NaN
31,31,Kayiwa International University,private,2015.0,Kampala,0.317654,32.557495,NaN
32,32,Kumi University,private,2004.0,Kumi,1.472971,33.863800,NaN
33,33,Livingstone International University,private,2011.0,Mbale,1.084230,34.179450,NaN
34,34,Metropolitan International University,private,2017.0,Kisoro,-1.282622,29.705030,NaN
35,35,Mountains of the Moon University,private,2018.0,Kabarole,0.659192,30.275433,Fort Portal
36,36,Muteesa I Royal University,private,2007.0,Kampala,0.306866,32.555138,NaN
37,37,Ndejje University,private,1992.0,Luwero,0.612578,32.475870,NaN
38,38,Nile University,private,2018.0,Arua,3.069826,30.937696,NaN
39,39,Nkumba University,private,1999.0,Wakiso,0.095291,32.506910,NaN
40,40,"Nkumba University, Kampala Campus",private,2015.0,NaN,0.306397,32.562252,NaN
41,41,Nsaka University,private,2013.0,Jinja,0.465645,33.205720,NaN
42,42,St. Augustine International University,private,2011.0,Kampala,0.272249,32.621635,NaN
43,43,St. Lawrence University,private,2007.0,Kampala,0.273007,32.617493,NaN
44,44,Stafford University,private,2015.0,Kampala,0.303736,32.605392,NaN
45,45,Team University,private,2015.0,Kampala,0.305952,32.561954,NaN
46,46,Uganda Christian University,private,1997.0,Mukono,0.357416,32.739845,NaN
47,47,Uganda Martyrs University,private,1993.0,Mpigi,0.002438,32.013910,NaN
48,48,Uganda Pentecostal University,private,2005.0,Kabarole,0.662259,30.266241,NaN
49,49,Uganda Technology and Management University,private,2013.0,Kampala,0.322074,32.621567,NaN
50,50,University of Kisubi,private,2009.0,Wakiso,0.121059,32.531834,NaN
51,51,University of the Sacred Heart Gulu,private,2016.0,Gulu,2.771576,32.266262,NaN
52,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
address = 'Stafford University'
params = { "key": API_KEY,
          'address': address
    
}
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
response = requests.get(base_url,params= params).json()
response.keys()
if response['status']== 'OK':
    geo = response['results'][0]['geometry']
    latitude = geo['location']['lat']
    longitude = geo['location']['lng']
print(latitude,longitude)

2.7702486 32.2665176

In [82]:
## new one 

def get_latitude(row):
    address = row['college']
    
    if pd.isna(address) or address == 'nan':
        return None

    params = {'key': API_KEY, 'address': address}
    base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'

    try:
        response = requests.get(base_url, params=params).json()
        if response['status'] == 'OK':
            geo = response['results'][0]['geometry']
            latitude = geo['location']['lat']
            return latitude
        else:
            print(f"Address '{address}' returned status {response['status']} for row index {row.name}")
            return None
    except Exception as e:
        print(f"Error fetching latitude for address '{address}' at row index {row.name}: {e}")
        return None
    finally:
        # Delay for 0.1 seconds (or any other suitable duration)
        time.sleep(1)

df['new_latitude'] = df.apply(get_latitude, axis=1)

Address 'Valley University of Science & Technology' returned status ZERO_RESULTS for row index 3
Address 'Victoria University' returned status ZERO_RESULTS for row index 4
Address 'Cavendish University' returned status ZERO_RESULTS for row index 21
Address 'International Business, Science, & Technology University' returned status ZERO_RESULTS for row index 25
Address 'Nkumba University' returned status ZERO_RESULTS for row index 39
Address 'Stafford University' returned status ZERO_RESULTS for row index 44
Address 'Team University' returned status ZERO_RESULTS for row index 45

Processed row index 0: 0.5452743999999999, 34.0200286
Processed row index 1: 2.7881388, 32.3168635
Processed row index 2: -1.2722888, 29.9882291
Address 'Valley University of Science & Technology' returned status ZERO_RESULTS at row index 3
Address 'Victoria University' returned status ZERO_RESULTS at row index 4
Processed row index 5: 1.373333, 32.290275
Processed row index 6: 0.3473946, 32.6320734
Processed row index 7: 2.2509766, 32.8210473
Processed row index 8: 0.3326347, 32.5685861
Processed row index 9: -0.6167245, 30.656788
Processed row index 10: 2.996229, 30.926812
Processed row index 11: 1.7655341, 33.627388
Processed row index 12: 0.3261291, 32.4410553
Processed row index 13: 0.2410963, 32.564848
Processed row index 14: 0.9400761, 30.8125638
Processed row index 15: 24.8920491, 67.0735131
Processed row index 16: 2.2461198, 32.8997326
Processed row index 17: -0.5738371999999999, 30.3813038
Processed row index 18: 0.3572723, 32.541461
Processed row index 19: -0.6032179999999999, 30.695261
Processed row index 20: 0.5702953, 32.6437524
Address 'Cavendish University' returned status ZERO_RESULTS at row index 21
Processed row index 22: 0.2921888, 32.6248196
Processed row index 23: 0.6649281, 30.2650646
Processed row index 24: -0.1228125, 30.5008125
Address 'International Business, Science, & Technology University' returned status ZERO_RESULTS at row index 25
Processed row index 26: 0.2858884, 32.6077911
Processed row index 27: 0.3157559, 32.5676531
Processed row index 28: 1.0989088, 34.1739858
Processed row index 29: 0.2943602, 32.6039696
Processed row index 30: 0.260514, 32.6352273
Processed row index 31: 0.3175252, 32.5574863
Processed row index 32: 1.4738125, 33.8638125
Processed row index 33: 1.0722986, 34.11485
Processed row index 34: 0.3407834, 32.5409809
Processed row index 35: 0.6590193, 30.27543
Processed row index 36: 0.3066408, 32.5551273
Processed row index 37: 0.6124352, 32.4762159
Processed row index 38: 30.0121847, 30.9868612
Address 'Nkumba University' returned status ZERO_RESULTS at row index 39
Processed row index 40: 0.306172, 32.5622505
Processed row index 41: 0.4641424, 33.2015039
Processed row index 42: 0.2723519, 32.6207375
Processed row index 43: 44.5892119, -75.1608814
Address 'Stafford University' returned status ZERO_RESULTS at row index 44
Address 'Team University' returned status ZERO_RESULTS at row index 45
Processed row index 46: 0.3552770000000001, 32.7392386
Processed row index 47: 0.0023491, 32.013828
Processed row index 48: 0.304831, 32.5466339
Processed row index 49: 0.3217631, 32.621356
Processed row index 50: 0.1208871, 32.5318131
Processed row index 51: 2.7702486, 32.2665176
Skipping invalid address at row index 52
Skipping invalid address at row index 53
Skipping invalid address at row index 54

In [86]:
df

,Unnamed: 0,college,unitype,estyr,district,latitude,longitude,city,new_latitude,new_longitude
0,0,Busitema University,public,2007.0,NaN,0.545462,34.020027,NaN,0.545274,34.020029
1,1,Gulu University,public,2002.0,NaN,2.788685,32.316868,NaN,2.788139,32.316863
2,2,Kabale University,public,2005.0,NaN,-1.241623,29.985659,NaN,-1.272289,29.988229
3,3,Valley University of Science & Technology,private,2015.0,Bushenyi,-0.547900,30.201128,NaN,None,None
4,4,Victoria University,private,2010.0,NaN,0.313821,32.589170,NaN,None,None
5,5,Virtual University of Uganda,private,2011.0,Kampala,0.301614,32.605907,NaN,1.373333,32.290275
6,6,Kyambogo University,public,2002.0,NaN,0.353579,32.630215,NaN,0.347395,32.632073
7,7,Lira University,public,2015.0,NaN,2.251234,32.821014,NaN,2.250977,32.821047
8,8,Makerere University,public,1922.0,NaN,0.329507,32.571056,NaN,0.332635,32.568586
9,9,Mbarara University of Science and Technology,public,1989.0,NaN,-0.616499,30.656788,NaN,-0.616725,30.656788
10,10,Muni University,public,2013.0,NaN,2.996486,30.926823,NaN,2.996229,30.926812
11,11,Soroti University,public,2015.0,NaN,1.765941,33.628796,NaN,1.765534,33.627388
12,12,Africa Renewal University,private,2013.0,Buloba-Mityana Road,0.326284,32.440525,NaN,0.326129,32.441055
13,13,African Bible University,private,2005.0,NaN,0.241361,32.564840,NaN,0.241096,32.564848
14,14,African Rural University,private,2011.0,Kibaale,0.942175,30.819237,NaN,0.940076,30.812564
15,15,Aga Khan University,private,2001.0,Kampala,0.320824,32.568980,NaN,24.892049,67.073513
16,16,"All Saints University, Lango",private,2008.0,Lira,2.246437,32.899900,NaN,2.24612,32.899733
17,17,Ankole Western University,private,2016.0,Sheema,-0.573634,30.381319,NaN,-0.573837,30.381304
18,18,Avance International University,private,2016.0,Wakiso,0.357508,32.541480,NaN,0.357272,32.541461
19,19,Bishop Stuart University,private,2006.0,Mbarara,-0.604102,30.694262,NaN,-0.603218,30.695261
20,20,Bugema University,private,1994.0,Luwero,0.570542,32.643784,NaN,0.570295,32.643752
21,21,Cavendish University,private,2008.0,Kampala,0.301162,32.593388,NaN,None,None
22,22,Clarke International University,private,2008.0,Kampala,0.305589,32.610924,NaN,0.292189,32.62482
23,23,Fins Medical University,private,2018.0,Kabrole,0.661393,30.265170,NaN,0.664928,30.265065
24,24,Ibanda University,private,2014.0,Ibanda,-0.122621,30.500774,NaN,-0.122813,30.500812
25,25,"International Business, Science, & Technology ...",private,2011.0,Kampala,0.334517,32.601337,NaN,None,None
26,26,International University of East Africa,private,2010.0,Kampala,0.286043,32.607834,NaN,0.285888,32.607791
27,27,Islamic Call University College,private,2011.0,Kampala,0.315949,32.567620,NaN,0.315756,32.567653
28,28,Islamic University in Uganda,private,1988.0,Mbale,1.103777,34.174255,NaN,1.098909,34.173986
29,29,Kampala International University,private,2001.0,Kampala,0.294823,32.605040,NaN,0.29436,32.60397
30,30,Kampala University,private,2000.0,Kampala,0.281009,32.540900,NaN,0.260514,32.635227
31,31,Kayiwa International University,private,2015.0,Kampala,0.317654,32.557495,NaN,0.317525,32.557486
32,32,Kumi University,private,2004.0,Kumi,1.472971,33.863800,NaN,1.473812,33.863813
33,33,Livingstone International University,private,2011.0,Mbale,1.084230,34.179450,NaN,1.072299,34.11485
34,34,Metropolitan International University,private,2017.0,Kisoro,-1.282622,29.705030,NaN,0.340783,32.540981
35,35,Mountains of the Moon University,private,2018.0,Kabarole,0.659192,30.275433,Fort Portal,0.659019,30.27543
36,36,Muteesa I Royal University,private,2007.0,Kampala,0.306866,32.555138,NaN,0.306641,32.555127
37,37,Ndejje University,private,1992.0,Luwero,0.612578,32.475870,NaN,0.612435,32.476216
38,38,Nile University,private,2018.0,Arua,3.069826,30.937696,NaN,30.012185,30.986861
39,39,Nkumba University,private,1999.0,Wakiso,0.095291,32.506910,NaN,None,None
40,40,"Nkumba University, Kampala Campus",private,2015.0,NaN,0.306397,32.562252,NaN,0.306172,32.56225
41,41,Nsaka University,private,2013.0,Jinja,0.465645,33.205720,NaN,0.464142,33.201504
42,42,St. Augustine International University,private,2011.0,Kampala,0.272249,32.621635,NaN,0.272352,32.620737
43,43,St. Lawrence University,private,2007.0,Kampala,0.273007,32.617493,NaN,44.589212,-75.160881
44,44,Stafford University,private,2015.0,Kampala,0.303736,32.605392,NaN,None,None
45,45,Team University,private,2015.0,Kampala,0.305952,32.561954,NaN,None,None
46,46,Uganda Christian University,private,1997.0,Mukono,0.357416,32.739845,NaN,0.355277,32.739239
47,47,Uganda Martyrs University,private,1993.0,Mpigi,0.002438,32.013910,NaN,0.002349,32.013828
48,48,Uganda Pentecostal University,private,2005.0,Kabarole,0.662259,30.266241,NaN,0.304831,32.546634
49,49,Uganda Technology and Management University,private,2013.0,Kampala,0.322074,32.621567,NaN,0.321763,32.621356
50,50,University of Kisubi,private,2009.0,Wakiso,0.121059,32.531834,NaN,0.120887,32.531813
51,51,University of the Sacred Heart Gulu,private,2016.0,Gulu,2.771576,32.266262,NaN,2.770249,32.266518
52,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
53,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None
54,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None

In [99]:
def get_lat(row):
    address = row['college']
   
    params = { "key": API_KEY,
          'address': address}
    base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
    response = requests.get(base_url,params= params).json()
    response.keys()
    if response['status']== 'OK':
        geo = response['results'][0]['geometry']
        latitude = geo['location']['lat']
        longitude = geo['location']['lng']
    return latitude

In [54]:
df['college'].iloc[3]

'Valley University of Science & Technology'

In [101]:
df['new_latitude'] = df['college'].apply(get_lat)

TypeError: string indices must be integers, not 'str'

In [57]:
df

,Unnamed: 0,college,unitype,estyr,district,latitude,longitude,city,new_latitude
0,0,Busitema University,public,2007.0,NaN,0.545462,34.020027,NaN,0.545274
1,1,Gulu University,public,2002.0,NaN,2.788685,32.316868,NaN,2.788139
2,2,Kabale University,public,2005.0,NaN,-1.241623,29.985659,NaN,-1.272289
3,3,Valley University of Science & Technology,private,2015.0,Bushenyi,-0.547900,30.201128,NaN,NaN
4,4,Victoria University,private,2010.0,NaN,0.313821,32.589170,NaN,NaN
5,5,Virtual University of Uganda,private,2011.0,Kampala,0.301614,32.605907,NaN,1.373333
6,6,Kyambogo University,public,2002.0,NaN,0.353579,32.630215,NaN,0.347395
7,7,Lira University,public,2015.0,NaN,2.251234,32.821014,NaN,2.250977
8,8,Makerere University,public,1922.0,NaN,0.329507,32.571056,NaN,0.332635
9,9,Mbarara University of Science and Technology,public,1989.0,NaN,-0.616499,30.656788,NaN,-0.616725
10,10,Muni University,public,2013.0,NaN,2.996486,30.926823,NaN,2.996229
11,11,Soroti University,public,2015.0,NaN,1.765941,33.628796,NaN,1.765534
12,12,Africa Renewal University,private,2013.0,Buloba-Mityana Road,0.326284,32.440525,NaN,0.326129
13,13,African Bible University,private,2005.0,NaN,0.241361,32.564840,NaN,0.241096
14,14,African Rural University,private,2011.0,Kibaale,0.942175,30.819237,NaN,0.940076
15,15,Aga Khan University,private,2001.0,Kampala,0.320824,32.568980,NaN,24.892049
16,16,"All Saints University, Lango",private,2008.0,Lira,2.246437,32.899900,NaN,2.246120
17,17,Ankole Western University,private,2016.0,Sheema,-0.573634,30.381319,NaN,-0.573837
18,18,Avance International University,private,2016.0,Wakiso,0.357508,32.541480,NaN,0.357272
19,19,Bishop Stuart University,private,2006.0,Mbarara,-0.604102,30.694262,NaN,-0.603218
20,20,Bugema University,private,1994.0,Luwero,0.570542,32.643784,NaN,0.570295
21,21,Cavendish University,private,2008.0,Kampala,0.301162,32.593388,NaN,NaN
22,22,Clarke International University,private,2008.0,Kampala,0.305589,32.610924,NaN,0.292189
23,23,Fins Medical University,private,2018.0,Kabrole,0.661393,30.265170,NaN,0.664928
24,24,Ibanda University,private,2014.0,Ibanda,-0.122621,30.500774,NaN,-0.122813
25,25,"International Business, Science, & Technology ...",private,2011.0,Kampala,0.334517,32.601337,NaN,NaN
26,26,International University of East Africa,private,2010.0,Kampala,0.286043,32.607834,NaN,0.285888
27,27,Islamic Call University College,private,2011.0,Kampala,0.315949,32.567620,NaN,0.315756
28,28,Islamic University in Uganda,private,1988.0,Mbale,1.103777,34.174255,NaN,1.098909
29,29,Kampala International University,private,2001.0,Kampala,0.294823,32.605040,NaN,0.294360
30,30,Kampala University,private,2000.0,Kampala,0.281009,32.540900,NaN,0.260514
31,31,Kayiwa International University,private,2015.0,Kampala,0.317654,32.557495,NaN,0.317525
32,32,Kumi University,private,2004.0,Kumi,1.472971,33.863800,NaN,1.473812
33,33,Livingstone International University,private,2011.0,Mbale,1.084230,34.179450,NaN,1.072299
34,34,Metropolitan International University,private,2017.0,Kisoro,-1.282622,29.705030,NaN,0.340783
35,35,Mountains of the Moon University,private,2018.0,Kabarole,0.659192,30.275433,Fort Portal,0.659019
36,36,Muteesa I Royal University,private,2007.0,Kampala,0.306866,32.555138,NaN,0.306641
37,37,Ndejje University,private,1992.0,Luwero,0.612578,32.475870,NaN,0.612435
38,38,Nile University,private,2018.0,Arua,3.069826,30.937696,NaN,30.012185
39,39,Nkumba University,private,1999.0,Wakiso,0.095291,32.506910,NaN,NaN
40,40,"Nkumba University, Kampala Campus",private,2015.0,NaN,0.306397,32.562252,NaN,0.306172
41,41,Nsaka University,private,2013.0,Jinja,0.465645,33.205720,NaN,0.464142
42,42,St. Augustine International University,private,2011.0,Kampala,0.272249,32.621635,NaN,0.272352
43,43,St. Lawrence University,private,2007.0,Kampala,0.273007,32.617493,NaN,44.589212
44,44,Stafford University,private,2015.0,Kampala,0.303736,32.605392,NaN,NaN
45,45,Team University,private,2015.0,Kampala,0.305952,32.561954,NaN,NaN
46,46,Uganda Christian University,private,1997.0,Mukono,0.357416,32.739845,NaN,0.355277
47,47,Uganda Martyrs University,private,1993.0,Mpigi,0.002438,32.013910,NaN,0.002349
48,48,Uganda Pentecostal University,private,2005.0,Kabarole,0.662259,30.266241,NaN,0.304831
49,49,Uganda Technology and Management University,private,2013.0,Kampala,0.322074,32.621567,NaN,0.321763
50,50,University of Kisubi,private,2009.0,Wakiso,0.121059,32.531834,NaN,0.120887
51,51,University of the Sacred Heart Gulu,private,2016.0,Gulu,2.771576,32.266262,NaN,2.770249
52,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
import requests
import time

def get_latitude(row):
    latitude = None
    address = row
    params = {'key': API_KEY, 'address': address}
    base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'

    for attempt in range(9):  # Try up to 3 attempts
        try:
            response = requests.get(base_url, params=params).json()
            if response['status'] == 'OK':
                geo = response['results'][0]['geometry']
                latitude = geo['location']['lat']
                break  # Exit loop if successful
            elif response['status'] == 'OVER_QUERY_LIMIT':
                print("Rate limit exceeded, waiting to retry...")
                time.sleep(4)  # Wait for 2 seconds before retrying
            else:
                print(f"Error or no result for address '{address}': {response['status']}")
                break  # Exit loop if an error other than rate limit exceeded
        except Exception as e:
            print(f"Exception fetching latitude for address '{address}': {e}")
            time.sleep(2)  # Wait for 2 seconds before retrying

    return latitude
df['new_latitude'] = df['college'].apply(get_latitude)

Error or no result for address 'Valley University of Science & Technology': ZERO_RESULTS
Error or no result for address 'Victoria University': ZERO_RESULTS
Error or no result for address 'Cavendish University': ZERO_RESULTS
Error or no result for address 'International Business, Science, & Technology University': ZERO_RESULTS
Error or no result for address 'Nkumba University': ZERO_RESULTS
Error or no result for address 'Stafford University': ZERO_RESULTS
Error or no result for address 'Team University': ZERO_RESULTS
Error or no result for address 'nan': ZERO_RESULTS
Error or no result for address 'nan': ZERO_RESULTS
Error or no result for address 'nan': ZERO_RESULTS

In [74]:
df.dtypes

Unnamed: 0        int64
college          object
unitype          object
estyr           float64
district         object
latitude        float64
longitude       float64
city             object
new_latitude    float64
dtype: object

In [24]:
print((0.5452743999999999-0.545462 ),( 34.0200286-34.020027))                #   0.545462 34.020027 0.545462	34.020027

-0.0001876000000000655 1.6000000044869012e-06

In [20]:
0.5452743999999999        34.0200286

-0.0005462000000000522

In [19]:
response['results'][0]['geometry']

{'location': {'lat': 2.7881388, 'lng': 32.3168635},
 'location_type': 'GEOMETRIC_CENTER',
 'viewport': {'northeast': {'lat': 2.789590480291502,
   'lng': 32.31824608029149},
  'southwest': {'lat': 2.786892519708498, 'lng': 32.3155481197085}}}

In [ ]:
def lat(df):
    df.

In [25]:
1.6000000044869012e-06

1.6000000044869012e-06